### ISSUE TITLE
Errors are swallowed insides blocks

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#479]
When a statement causes an error inside a block, the execution of that block is halted, but the error is swallowed:

    > [1,2,3].each do |i| puts i; i.abc; puts 2*i end
    1
    2
    3
    #> [1, 2, 3]

**Comment by st0012** [comment]
This should be fixed in #475

**Comment by st0012** [comment]
@saveriomiroddi Can you help me confirm if this issue is fixed?

**Comment by saveriomiroddi** [comment]
I think this should be captured in a UT, as it's a quite important functionality.

**Comment by st0012** [comment]
@saveriomiroddi It'll be very hard to write unit test for this case. The main issue would be writing the block's VM instructions by ourselves, which will be very messy.

Also, even we do write those instructions by ourselves, Goby's instruction format and spec are still unstable now. I think it'll be better to write unit tests after like version `0.5.0`.

**Comment by saveriomiroddi** [comment]
ok :+1: the issue is still present in the current `master` branch.

**Comment by st0012** [comment]
I think this is caused by the REPL environment. I ran the code above in normal a script and it functions well.
If you can see proper error in normal evaluation, can you help me close this issue and create a new one to specify this problem now only happen in REPL?
